#!/usr/bin/env python3
"""Build the E214 four-ablation LaTeX table (booktabs), same style as
overall_comparison_nojerk.tex.

Reads results/E214/reports/e214_ablation_overall.tsv (metric, series, mean, std,
worst, n, wilcoxon_p) and emits ablation_table.tex.

Columns: Ours (full method) + 4 leave-one-out ablations.
  -SB   = remove surface_band  (fine SDF surface term)      [Contribution 1]
  -HDMI = remove contact_hdmi   (coarse anchor attraction)   [Contribution 1]
  -gate = remove all hard candidate gates                    [Contribution 2]
  -pen  = remove all soft penalties (+E167A z)               [Contribution 2]

Ours column is bold; an ablation cell carries ^{*} when it differs from Ours at
paired Wilcoxon p<0.05.
"""

from __future__ import annotations

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[5]
TSV = REPO / "workspace/core4d/results/E214/reports/e214_ablation_overall.tsv"
OUT = Path(__file__).resolve().parent / "ablation_table.tex"

SERIES = ["full", "A1_contactHDMI_only", "A2_surfaceBand_only",
          "A3_softPenalty_only", "A4_hardGate_only"]

# metric_key, label, arrow, format, group-break-before
ROWS = [
    ("contact_3mm",    r"Phys. contact@3mm", r"\uparrow",   "{:.3f}", False),
    ("pen_3mm",        r"Phys. pen@3mm",     r"\downarrow", "{:.3f}", False),
    ("geom_2mm",       r"Geom. pen@2mm",     r"\downarrow", "{:.3f}", False),
    ("track_root_pos", r"Root pos err (cm)", r"\downarrow", "{:.2f}", True),
    ("track_root_ori", r"Root ori err (deg)", r"\downarrow", "{:.2f}", False),
    ("track_eef_pos",  r"EEF pos err (cm)",  r"\downarrow", "{:.2f}", False),
    ("track_eef_ori",  r"EEF ori err (deg)", r"\downarrow", "{:.2f}", False),
    ("track_obj_pos",  r"Obj pos err (cm)",  r"\downarrow", "{:.2f}", False),
    ("track_obj_ori",  r"Obj ori err (deg)", r"\downarrow", "{:.2f}", False),
    ("obj_speed",      r"Obj speed max (m/s)", r"\downarrow", "{:.2f}", True),
    ("foot_slip",      r"Foot slip max (m)", r"\downarrow", "{:.2f}", False),
]


def load() -> dict[tuple[str, str], dict]:
    out: dict[tuple[str, str], dict] = {}
    with TSV.open() as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            out[(r["metric"], r["series"])] = r
    return out


def cell(data, metric, series, fmt) -> str:
    r = data.get((metric, series))
    if r is None or r["mean"] == "":
        return "--"
    val = fmt.format(float(r["mean"]))
    if series == "full":
        return rf"\textbf{{{val}}}"
    p = r.get("wilcoxon_p", "")
    try:
        star = "$^{*}$" if (p != "" and float(p) < 0.05) else ""
    except ValueError:
        star = ""
    return f"{val}{star}"


def main() -> int:
    data = load()
    lines = [
        r"% Auto-generated by build_ablation_table.py -- E214 four-ablation study.",
        r"% Requires: \usepackage{booktabs}.",
        r"",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Leave-one-out ablation of the two core contributions on "
        r"CORE4D-G1 (50 sequences; the two E167A box021 cases are dropped and "
        r"box023 uses the full-stack baseline so all baselines are homogeneous). "
        r"Each ablation removes one sub-component and re-runs the sampling-based "
        r"MPC; \textbf{Ours} is the full method. "
        r"\emph{Contribution 1 (Multi-Scale Contact)}: $-$SB removes the fine "
        r"SDF surface-band term, $-$HDMI removes the coarse anchor-attraction "
        r"term. \emph{Contribution 2 (Part-wise Penetration)}: $-$gate removes "
        r"all hard candidate gates, $-$pen removes all soft penetration "
        r"penalties. $\uparrow$/$\downarrow$: higher/lower is better; "
        r"$^{*}$ marks a paired Wilcoxon difference from Ours at $p<0.05$. "
        r"Note $-$HDMI's \emph{lower} penetration is an artifact of failing to "
        r"reach the object (see EEF pos err), not better contact.}",
        r"\label{tab:ablation}",
        r"\begin{tabular}{l ccccc}",
        r"\toprule",
        r"Metric & Ours & $-$SB & $-$HDMI & $-$gate & $-$pen \\",
        r"\midrule",
    ]
    for metric, label, arrow, fmt, brk in ROWS:
        if brk:
            lines.append(r"\midrule")
        cells = " & ".join(cell(data, metric, s, fmt) for s in SERIES)
        lines.append(rf"{label} ${arrow}$ & {cells} \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
