#!/usr/bin/env python3
"""E214 four-ablation LaTeX table (booktabs) -- Overall, 47-case set.

Reads results/E214/reports/exclude_floor3/e214_ablation_overall.tsv (the Overall
aggregation over the 47-case set = 50 paper cases minus 3 floor-effect cases) and
emits ablation_table_47.tex.

Reported metrics (user-selected subset + whole-body MPJPE):
  Phys. contact@5mm   physical hand-object contact within 5mm, in the ref mask
  Phys. pen@5mm       physical hand-object penetration deeper than 5mm
  MPJPE (cm)          mean per-joint Cartesian error over ALL robot bodies
  Obj pos err (cm)    object position tracking error
  Obj ori err (deg)   object orientation tracking error
  Foot skate mean/max horizontal skating speed of a stance foot (m/s)

Columns: Ours (full) + 4 leave-one-out ablations, mapped to the two contributions.
  -SB   = remove surface_band  (fine SDF surface term)      [Contribution 1]  (A1)
  -HDMI = remove contact_hdmi   (coarse anchor attraction)   [Contribution 1]  (A2)
  -gate = remove all hard candidate gates                    [Contribution 2]  (A3)
  -pen  = remove all soft penalties (+E167A z)               [Contribution 2]  (A4)
Ours column is bold.
"""

from __future__ import annotations

import csv
from pathlib import Path

REPO = Path(__file__).resolve().parents[5]
TSV = REPO / "workspace/core4d/results/E214/reports/exclude_floor3/e214_ablation_overall.tsv"
OUT = Path(__file__).resolve().parent / "ablation_table_47.tex"

SERIES = ["full", "A1_contactHDMI_only", "A2_surfaceBand_only",
          "A3_softPenalty_only", "A4_hardGate_only"]

# metric_key, label, arrow, kind, group-break-before
# kind: pct (mean*100, %) | cm | deg | mps
ROWS = [
    ("contact_5mm",    r"Phys. contact@5mm ($\%$)", r"\uparrow",   "pct", False),
    ("pen_5mm",        r"Phys. pen@5mm ($\%$)",     r"\downarrow", "pct", False),
    ("track_mpjpe_g",  r"MPJPE-G (cm)",             r"\downarrow", "cm",  True),
    ("track_mpjpe_l",  r"MPJPE-L (cm)",             r"\downarrow", "cm",  False),
    ("track_obj_pos",  r"Obj pos err (cm)",         r"\downarrow", "cm",  False),
    ("track_obj_ori",  r"Obj ori err (deg)",        r"\downarrow", "deg", False),
    ("foot_skate_mean", r"Foot skate mean (m/s)",   r"\downarrow", "mps", True),
    ("foot_skate_max", r"Foot skate max (m/s)",     r"\downarrow", "mps", False),
]


def load() -> dict[tuple[str, str], dict]:
    out: dict[tuple[str, str], dict] = {}
    with TSV.open() as fh:
        for r in csv.DictReader(fh, delimiter="\t"):
            out[(r["metric"], r["series"])] = r
    return out


def fmt(mean: float, kind: str) -> str:
    if kind == "pct":
        return f"{mean * 100:.1f}"
    if kind in ("cm", "deg"):
        return f"{mean:.2f}"
    if kind == "mps":
        return f"{mean:.3f}"
    return f"{mean:.3g}"


def cell(data, metric, series, kind) -> str:
    r = data.get((metric, series))
    if r is None or r["mean"] == "":
        return "--"
    val = fmt(float(r["mean"]), kind)
    return rf"\textbf{{{val}}}" if series == "full" else val


def main() -> int:
    data = load()
    lines = [
        r"% Auto-generated by build_ablation_table_47.py -- E214 four-ablation (Overall, 47 cases).",
        r"% Requires: \usepackage{booktabs}.",
        r"",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Leave-one-out ablation of the two core contributions on "
        r"CORE4D-G1 (47 sequences: the 50-case paper set minus three floor-effect "
        r"cases whose full-method result is already degenerate). Each ablation "
        r"removes one sub-component and re-runs the sampling-based MPC; "
        r"\textbf{Ours} is the full method. \emph{Contribution 1 (Multi-Scale "
        r"Contact)}: $-$SB removes the fine SDF surface-band term, $-$HDMI removes "
        r"the coarse anchor-attraction term. \emph{Contribution 2 (Part-wise "
        r"Penetration)}: $-$gate removes all hard candidate gates, $-$pen removes "
        r"all soft penetration penalties. MPJPE is the mean per-joint Cartesian "
        r"error over all robot links (whole-body, not just root/eef): MPJPE-G is "
        r"global, MPJPE-L is pelvis-aligned (pose only). "
        r"$\uparrow$/$\downarrow$: higher/lower is better. Note $-$HDMI's lower "
        r"penetration is an artifact of failing to reach the object (see MPJPE-G), "
        r"not better contact.}",
        r"\label{tab:ablation}",
        r"\begin{tabular}{l ccccc}",
        r"\toprule",
        r"Metric & Ours & $-$SB & $-$HDMI & $-$gate & $-$pen \\",
        r"\midrule",
    ]
    for metric, label, arrow, kind, brk in ROWS:
        if brk:
            lines.append(r"\midrule")
        cells = " & ".join(cell(data, metric, s, kind) for s in SERIES)
        lines.append(rf"{label} ${arrow}$ & {cells} \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
