#!/usr/bin/env python3
"""E062: per-case auto-derive contact_hdmi_palm_normal from ref motion.

Reads ref qpos, runs forward kinematics on the case's scene_act.xml, computes
which wrist-local axis (+/- x/y/z) most consistently points toward the object
center across the proximity window, and writes a yaml override.

Usage:
    .venv/bin/python workspace/core4d/scripts/convert/compute_palm_normal.py \\
        --cases box025_person1 box023_person1

Outputs:
    examples/config/override/core4d_e062_<case>.yaml

Algorithm (matches audit log 70 sec 2.2):
1. Load qpos_ref from trajectory_kinematic_dual.npz (fallback: trajectory_kinematic.npz)
2. For each frame, mj_kinematics to get wrist xpos/xmat and object xpos
3. If wrist-object distance < proximity_threshold (default 0.30m), accumulate:
   - For each candidate local axis (+/- x, +/- y, +/- z):
       dot = (wrist_xmat @ axis_local) . normalize(obj_pos - wrist_pos)
4. Pick axis with max mean dot per side; emit unit vector in wrist-local frame
"""
from __future__ import annotations

import argparse
from pathlib import Path

import mujoco
import numpy as np

CANDIDATE_AXES = np.array(
    [
        [+1, 0, 0],
        [-1, 0, 0],
        [0, +1, 0],
        [0, -1, 0],
        [0, 0, +1],
        [0, 0, -1],
    ],
    dtype=float,
)
AXIS_LABELS = ["+x", "-x", "+y", "-y", "+z", "-z"]


def compute_palm_normal_for_case(
    case_name: str,
    scene_xml: str,
    ref_npz: str,
    obj_body_name: str = "object",
    wrist_body_names: tuple[str, str] = (
        "left_wrist_yaw_link",
        "right_wrist_yaw_link",
    ),
    proximity_threshold: float = float("inf"),
) -> dict[str, list[float]]:
    m = mujoco.MjModel.from_xml_path(scene_xml)
    d = mujoco.MjData(m)
    obj_bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, obj_body_name)
    if obj_bid < 0:
        raise RuntimeError(f"{case_name}: object body '{obj_body_name}' not found")
    wrist_bids = []
    for n in wrist_body_names:
        bid = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_BODY, n)
        if bid < 0:
            raise RuntimeError(f"{case_name}: wrist body '{n}' not found")
        wrist_bids.append(bid)

    qpos_ref = np.load(ref_npz)["qpos"]
    if qpos_ref.ndim == 3:
        qpos_ref = qpos_ref[:, 0, :]

    nq_use = min(qpos_ref.shape[1], m.nq)

    dot_sums = {bid: np.zeros(6) for bid in wrist_bids}
    counts = {bid: 0 for bid in wrist_bids}

    for t in range(qpos_ref.shape[0]):
        d.qpos[:nq_use] = qpos_ref[t, :nq_use]
        mujoco.mj_kinematics(m, d)
        obj_pos = d.xpos[obj_bid].copy()
        for bid in wrist_bids:
            wrist_pos = d.xpos[bid]
            wrist_mat = d.xmat[bid].reshape(3, 3)
            dir_to_obj = obj_pos - wrist_pos
            dist = float(np.linalg.norm(dir_to_obj))
            if dist > proximity_threshold:
                continue
            dir_unit = dir_to_obj / max(dist, 1e-6)
            for i in range(6):
                axis_world = wrist_mat @ CANDIDATE_AXES[i]
                dot_sums[bid][i] += float(np.dot(axis_world, dir_unit))
            counts[bid] += 1

    result: dict[str, list[float]] = {}
    for side, bid in zip(["left", "right"], wrist_bids):
        n = counts[bid]
        if n == 0:
            print(
                f"[WARN] {case_name} {side}: 0 frames within {proximity_threshold}m; "
                "falling back to [0,0,0] (no prior)"
            )
            result[side] = [0.0, 0.0, 0.0]
            continue
        means = dot_sums[bid] / n
        best_idx = int(np.argmax(means))
        result[side] = [float(v) for v in CANDIDATE_AXES[best_idx]]
        means_str = ", ".join(
            f"{lbl}={means[i]:+.3f}" for i, lbl in enumerate(AXIS_LABELS)
        )
        print(
            f"[{case_name}] {side:5s}: n={n:3d}  {means_str}  "
            f"-> {AXIS_LABELS[best_idx]} {result[side]}"
        )
    return result


def write_yaml_override(case_name: str, palm_normal: dict[str, list[float]], out_dir: Path) -> Path:
    yaml_path = out_dir / f"core4d_e062_{case_name.replace('_person1', '').replace('_person2', '')}.yaml"
    content = f"""# @package _global_
# E062 X1: auto-derived palm_normal for {case_name} (sphere geometry, E041c base).
# Generated by workspace/core4d/scripts/convert/compute_palm_normal.py.
# Method: ref-motion proximity-windowed dot product (audit log 70 sec 2.2 algorithm).
defaults:
  - core4d_e041c
  - _self_

contact_hdmi_palm_normal_left:  {palm_normal['left']}
contact_hdmi_palm_normal_right: {palm_normal['right']}
"""
    yaml_path.write_text(content)
    print(f"  -> wrote {yaml_path}")
    return yaml_path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", nargs="+", required=True, help="case names, e.g. box025_person1")
    ap.add_argument(
        "--out-dir",
        default="examples/config/override",
        help="output dir for yaml overrides",
    )
    ap.add_argument(
        "--proximity-threshold",
        type=float,
        default=float("inf"),
        help="meters; only count frames where wrist-to-object_center < threshold. "
        "Default inf (all frames) since wrist orientation is consistent in approach phase.",
    )
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    base = Path("example_datasets/processed/core4d/unitree_g1/humanoid_object")
    for case in args.cases:
        case_dir = base / case
        # Use scene.xml (kinematic, freejoint object) not scene_act.xml (PD-controlled object)
        # so that loaded qpos_ref matches the model nq exactly.
        scene_xml = case_dir / "scene.xml"
        if not scene_xml.exists():
            print(f"[SKIP] {case}: {scene_xml} missing")
            continue
        # Try _dual then plain (run_mjwp.py preferred order)
        ref_npz = None
        for ref_name in ("trajectory_kinematic_dual.npz", "trajectory_kinematic.npz"):
            cand = case_dir / "0" / ref_name
            if cand.exists():
                ref_npz = cand
                break
        if ref_npz is None:
            print(f"[SKIP] {case}: no ref npz in {case_dir / '0'}")
            continue
        print(f"=== {case}  scene={scene_xml.name}  ref={ref_npz.name} ===")
        result = compute_palm_normal_for_case(
            case, str(scene_xml), str(ref_npz), proximity_threshold=args.proximity_threshold
        )
        write_yaml_override(case, result, out_dir)


if __name__ == "__main__":
    main()
